try:
    # TODO 後で削除する
    raise ValueError()
except ValueError:
    print("Do Something")
    # exceptされたエラーをraiseする
    raise